pub struct W<T>(pub T);

pub static NAMES: &[&'static str] = &[
    "ARKADY DARELL",
    "BEL RIOSE",
    "CLEON I",
    "DORS VENABILI",
    "EBLING MIS",
    "GAAL DORNICK",
    "HARI SELDON",
    "HOBER MALLOW",
    "JANOV PELORAT",
    "THE MULE",
    "PREEM PALVER",
    "R.D. OLIVAW",
    "R.G. REVENTLOV",
    "RAYCH SELDON",
    "SALVOR HARDIN",
    "WANDA SELDON",
    "YUGO AMARYL",
    "JAMES T. KIRK",
    "LEONARD MCCOY",
    "HIKARU SULU",
    "MONTGOMERY SCOTT",
    "SPOCK",
    "PICARD",
    "CHRISTINE CHAPEL",
    "NYOTA UHURA",
    "PAVEL CHEKOV",
    "FORD",
    "ZAPHOD",
    "MARVIN",
    "ANAKIN",
    "LUKE",
    "LEIA",
    "ACKBAR",
    "TARKIN",
    "JABBA",
    "REY",
    "KYLO",
    "HAN",
    "VADER",
    "D.A.R.Y.L.",
    "HAL 9000",
    "LYTA ALEXANDER",
    "STEPHEN FRANKLIN",
    "LENNIER",
];
